In [12]:
from abc import *

class Animal():
    def __init__(self):
        self.hungry = 0
    def sound(self):
        raise NotImplementedError
        self.hungry -= 10
        print("Ate",self.hungry)
    def walk(self):
        self.hungry += 10
        print("Walk", self.hungry)

class Dog(Animal):
    def __init__(self):
        super().__init__()

    def eat(self):
        super().eat()
        print("LL")


In [ ]:
class Car():
    total_num = 0
        
    @classmethod
    def get_total_car(cls): #put cls instead of self
        return cls.total_num

    def __init__(self,name,capacity,year):
        self.name = name
        self.capacity = capacity
        self.year = year
        
        Car.total_num += 1
        
    def get_name(self):
        print(self.name)
    def get_cc(self):
        print(self.capacity)
    def get_year(self):
        print(self.year)
    
    def name_changer(self):
        print(self.name)
        a = input()
        self.name = a
    def rank(self):
        if self.capacity <= 1000:
            print("small")
        if self.capacity >= 1000 and self.capacity < 2000:
            print("medium")
        if self.capacity >= 2000:
            print("large")
            

In [ ]:
car1 = Car("BMW",1500,2018)

In [ ]:
print(car1.name)
car1.name_changer()

qwd
qwd


In [69]:
car1.get_name()

qwd


In [70]:
car1.capacity

1500

In [71]:
car1.rank()

medium


In [ ]:
class Car(object):
    
    total = 0
    year_dict = {}
    
    def __init__(self, name, cc, year):
        self.__name = name
        self.__cc = cc
        self.__year = year
        
        Car.total += 1
        
        if self.__year not in Car.year_dict:
            Car.year_dict[self.__year].append(self)
            
    @classmethod
    def get_cars_by_year(cls, year):
        year_dict = cls.year_dict
        
        if year not in year_dict:
            return []
        else:
            return year_dict[year]
        
    #method
    def change_name(self, new_name):
        self.__name = new_name
        return self.__name
    
    #staticmethod
    def temp_static(self):
        pass
    
    

In [7]:
x = [1, 2, 3]

try:
    x[1]
#    x[5]
#    print(10 / 0)
except ZeroDivisionError as e:
     print("숫자를 0으로 나눌수 없음", e)
except IndexError as e:
    print("잘못된 인덱스", e)
else:
    print("no error")
finally:
    print("finally executed")

숫자를 0으로 나눌수 없음 division by zero
finally executed


In [8]:
try:
    raise Exception("msg")
except:
    print("error solved")

error solved


In [9]:
class MyException(Exception):
    pass

In [11]:
try:
    raise MyException("my error")
except MyException as e:
    print("this is my exception")
    print(e)

this is my exception
my error


In [16]:
import sys
import random

In [18]:
%%writefile calc.py

def calc_sum(a,b):
    return a+b
def calc_mul(a,b):
    return a*b
def calc_sub(a,b):
    return a-b

Writing calc.py


In [19]:
import calc

In [20]:
calc.calc_sum(20,531)

551

In [21]:
from calc import calc_sum

In [22]:
calc_sum(12,124)

136

# Numpy

In [24]:
import numpy as np
a = np.array(range(10))

In [27]:
l1 = [5,4,8,10]
b = np.array(l1)

In [28]:
l2 = [1,2.0,3]
l2

[1, 2.0, 3]

In [31]:
np.array(l2)

array([1., 2., 3.])

In [34]:
a.shape
b.shape

(4,)

In [39]:
l1 =[[1,2],[3,4]]
a = np.array(l1)
a

array([[1, 2],
       [3, 4]])

In [40]:
a.shape

(2, 2)

In [41]:
l2 = [[1,2,3],[4,5]]
b = np.array(l2)
b

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.linspace(10,20,9)

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [46]:
a= np.arange(2,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a.shape

(8,)

In [55]:
b = a.reshape(2,4)
b

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [56]:
a = np.linspace(0,100)

In [57]:
b = a.astype(str)
b

array(['0.0', '2.0408163265306123', '4.081632653061225',
       '6.122448979591837', '8.16326530612245', '10.204081632653061',
       '12.244897959183675', '14.285714285714286', '16.3265306122449',
       '18.367346938775512', '20.408163265306122', '22.448979591836736',
       '24.48979591836735', '26.53061224489796', '28.571428571428573',
       '30.612244897959183', '32.6530612244898', '34.69387755102041',
       '36.734693877551024', '38.775510204081634', '40.816326530612244',
       '42.85714285714286', '44.89795918367347', '46.93877551020408',
       '48.9795918367347', '51.02040816326531', '53.06122448979592',
       '55.10204081632653', '57.142857142857146', '59.183673469387756',
       '61.224489795918366', '63.26530612244898', '65.3061224489796',
       '67.34693877551021', '69.38775510204081', '71.42857142857143',
       '73.46938775510205', '75.51020408163265', '77.55102040816327',
       '79.59183673469389', '81.63265306122449', '83.6734693877551',
       '85.71428571428572

In [58]:
c = a.astype(int)
c

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [60]:
np.random.randn(2,2)

array([[-0.54650912,  0.47871183],
       [-0.4552222 ,  0.91704334]])

In [62]:
a = np.linspace(1,20,9)

In [63]:
a.reshape(3,3)

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [66]:
a[:]

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

### vector

In [67]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
a+a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [73]:
np.arange(10) + np.arange(50,60)

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68])