# Numpy & Arrays

In [1]:
import numpy as np

In [2]:
data1 = range(10)
arr1 = np.array(data1)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import random

In [4]:
data3 = [random.uniform(-1,1) for i in range(10)]
arr3 =np.array(data3)
arr3

array([ 0.96998101, -0.08864635,  0.70172481, -0.07160186, -0.12445333,
       -0.13353566,  0.23860251,  0.21144362, -0.15792454,  0.32228729])

In [5]:
data5 = [[1,2,3],[4,5,6],[7,8,9]]
arr5 = np.array(data5)
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr5.shape

(3, 3)

### arange & linspace

In [7]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr3 = np.linspace(0,np.pi,20)
arr3

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [9]:
len(arr3)

20

In [10]:
arr4 = np.arange(16)
arr4.reshape(2,8)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### rand

In [11]:
arr1 = np.random.rand(0,10)
arr1

array([], shape=(0, 10), dtype=float64)

In [12]:
rand_n_arr = np.random.randn(5,5)
rand_n_arr

array([[-0.04444738,  1.23025289, -0.56797045, -1.08224653,  2.6600017 ],
       [ 1.07791664, -0.19509283,  1.11483384, -0.97440379, -0.09058435],
       [-0.0441557 ,  0.40082892, -0.65761028, -0.49608084,  0.55889514],
       [ 0.77479569,  0.46552529,  1.1877571 , -0.64774286, -0.17427282],
       [-1.09717437,  0.80892651, -0.95077806,  0.52983197, -2.90958879]])

### 2 dim array

In [13]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr1[1][1] = 30
arr1

array([[ 0,  1,  2],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [15]:
arr1[0,2]

2

In [16]:
arr1[0][2]

2

In [17]:
arr1[[0,2]]

array([[0, 1, 2],
       [6, 7, 8]])

In [18]:
arr1[0,2] = 10
arr1

array([[ 0,  1, 10],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [19]:
arr1[2] = [3,4,5]
arr1

array([[ 0,  1, 10],
       [ 3, 30,  5],
       [ 3,  4,  5]])

In [20]:
arr1[1:,1:]

array([[30,  5],
       [ 4,  5]])

In [21]:
arr1[1:,1:] = np.array([[1,2],[3,4]])
arr1

array([[ 0,  1, 10],
       [ 3,  1,  2],
       [ 3,  3,  4]])

In [22]:
arr1 = np.arange(10,100,10)
arr1[arr1>50]

array([60, 70, 80, 90])

In [23]:
arr2 = np.arange(10,170,10).reshape(4,4)
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [24]:
arr2[arr2%4==0]

array([ 20,  40,  60,  80, 100, 120, 140, 160])

In [25]:
arr2[arr2%4==0].reshape(2,4)

array([[ 20,  40,  60,  80],
       [100, 120, 140, 160]])

In [26]:
arr2[:-1:2,::2]

array([[ 10,  30],
       [ 90, 110]])

### NaN & Inf

In [27]:
np.nan

arr1 = np.array([1,2,3, np.nan, np.inf])
arr1

array([ 1.,  2.,  3., nan, inf])

In [28]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
arr1[[1,2],[0,1]]

array([3, 7])

### Special shapes

In [30]:
arr_zero_n = np.zeros(9)
arr_zero_n

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
arr_zero_mxn = np.zeros((3,3))
arr_zero_mxn

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
arr_one_n = np.ones(9)
arr_one_n

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
arr_I2 = np.identity(5)
arr_I2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Operations

In [34]:
arr1 = np.arange(1.0,7)
arr2 = np.arange(10.0,70,10)

#repr = representative
print('arr1: %s \t shape:%s' % (repr(arr1), arr1.shape))
print('arr2: %s \t shape:%s' % (repr(arr2), arr2.shape))

arr1: array([1., 2., 3., 4., 5., 6.]) 	 shape:(6,)
arr2: array([10., 20., 30., 40., 50., 60.]) 	 shape:(6,)


In [35]:
arr1 + arr2
arr1/3
arr1**2
arr2[0]>20

False

In [36]:
arr1 = np.arange(1,9).reshape(2,4)

arr2 = np.arange(10,90,10).reshape(2,4)

print('arr1: %s \t\t shape:%s' % (repr(arr1), arr1.shape))
print('arr2: %s \t shape:%s' % (repr(arr2), arr2.shape))

arr1: array([[1, 2, 3, 4],
       [5, 6, 7, 8]]) 		 shape:(2, 4)
arr2: array([[10, 20, 30, 40],
       [50, 60, 70, 80]]) 	 shape:(2, 4)


In [37]:
arr1*arr2

array([[ 10,  40,  90, 160],
       [250, 360, 490, 640]])

In [38]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr1.sum(), arr1.mean(), arr1.std(), arr1.var()

(55, 5.5, 2.8722813232690143, 8.25)

In [40]:
arr1.cumsum(), arr1.cumprod()
#cumulative sum, cumulative product

(array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32),
 array([      1,       2,       6,      24,     120,     720,    5040,
          40320,  362880, 3628800], dtype=int32))

In [41]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(6, 0, -1).reshape(3, 2)

print("A: %s" % repr(A))
print("B: %s" % repr(B))

A: array([[1, 2, 3],
       [4, 5, 6]])
B: array([[6, 5],
       [4, 3],
       [2, 1]])


In [42]:
np.dot(A,B)

array([[20, 14],
       [56, 41]])

In [43]:
A.T, A.transpose()

(array([[1, 4],
        [2, 5],
        [3, 6]]), array([[1, 4],
        [2, 5],
        [3, 6]]))

In [44]:
B = np.arange(4, 0, -1).reshape(2, 2)
Bi = np.linalg.inv(B)
Bi #inverse matrix

array([[-0.5,  1.5],
       [ 1. , -2. ]])

In [45]:
i = np.eye(2).astype(int)
i

array([[1, 0],
       [0, 1]])

In [46]:
np.linalg.inv(i).astype(int)

array([[1, 0],
       [0, 1]])

# Module & Packages

In [47]:
from random import *

In [48]:
random()

0.37807264789103534

In [49]:
from json import encoder

In [50]:
import json.encoder

In [51]:
import sys

In [52]:
sys.path

['C:\\Users\\student\\Documents\\python project',
 'C:\\ProgramData\\Anaconda3\\python37.zip',
 'C:\\ProgramData\\Anaconda3\\DLLs',
 'C:\\ProgramData\\Anaconda3\\lib',
 'C:\\ProgramData\\Anaconda3',
 '',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\student\\.ipython']

# Pandas

In [53]:
import numpy as np
import pandas as pd

In [54]:
s = pd.Series([1,3,5, np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [55]:
s1 = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s1.index)
print(s1.values)

RangeIndex(start=0, stop=6, step=1)
[ 1.  3.  5. nan  6.  8.]


In [56]:
s1 = pd.Series([np.nan, np.inf, 0, 1, 2, 3, 'a', 'b', 'c'])
s1

0    NaN
1    inf
2      0
3      1
4      2
5      3
6      a
7      b
8      c
dtype: object

In [57]:
s1.values

array([nan, inf, 0, 1, 2, 3, 'a', 'b', 'c'], dtype=object)

In [58]:
s2 = pd.Series(data = range(10,20), index = range(10))
s2

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [59]:
index_date = ['2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20']
s3 = pd.Series([200, 195, np.nan, 205], index=index_date)
s3

2018-10-17    200.0
2018-10-18    195.0
2018-10-19      NaN
2018-10-20    205.0
dtype: float64

In [60]:
s1 = pd.Series(range(10,70,10))
s1

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [61]:
s2 = pd.Series(range(1,6))
s2

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [62]:
s1+s2 #5th index -> NaN since no value

0    11.0
1    22.0
2    33.0
3    44.0
4    55.0
5     NaN
dtype: float64

In [63]:
pd.date_range('2019-05-25','2019-05-28')

DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28'], dtype='datetime64[ns]', freq='D')

In [64]:
pd.date_range('2019-05-25 10:00:00', periods = 6)

DatetimeIndex(['2019-05-25 10:00:00', '2019-05-26 10:00:00',
               '2019-05-27 10:00:00', '2019-05-28 10:00:00',
               '2019-05-29 10:00:00', '2019-05-30 10:00:00'],
              dtype='datetime64[ns]', freq='D')

In [65]:
date_index1 = pd.date_range(start='2019-05-25', periods=4)
date_index2 = pd.date_range(start='2019.05.25', periods=4)
date_index3 = pd.date_range(start='2019/05/25', periods=4)
print('date_index1: ', repr(date_index1))
print('date_index2: ', repr(date_index2))
print('date_index3: ', repr(date_index3))

date_index4 = pd.date_range(start='05/25/2019', periods=4)
date_index5 = pd.date_range(start='05-25-2019', periods=4)
date_index6 = pd.date_range(start='05.25.2019', periods=4)

print('date_index4: ', repr(date_index4))
print('date_index5: ', repr(date_index5))
print('date_index6: ', repr(date_index6))

date_index1:  DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28'], dtype='datetime64[ns]', freq='D')
date_index2:  DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28'], dtype='datetime64[ns]', freq='D')
date_index3:  DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28'], dtype='datetime64[ns]', freq='D')
date_index4:  DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28'], dtype='datetime64[ns]', freq='D')
date_index5:  DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28'], dtype='datetime64[ns]', freq='D')
date_index6:  DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28'], dtype='datetime64[ns]', freq='D')


### Dataframe

In [66]:
df = pd.DataFrame([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
df

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [67]:
np_array = np.arange(10,100,10).reshape(3,3)
df1 = pd.DataFrame(np_array)
df1

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [68]:
df1.index = pd.date_range('2019-05-05',periods=3)
df1

0   1   2
2019-05-05  10  20  30
2019-05-06  40  50  60
2019-05-07  70  80  90

In [69]:
df1.columns = ["A","B","C"]
df1

A   B   C
2019-05-05  10  20  30
2019-05-06  40  50  60
2019-05-07  70  80  90

In [70]:
table_data = {'연도':list(range(2010, 2020)),
              '매출액': [v**2 for i, v in enumerate(range(1,11))],
              '종업원 수': list(range(2, 30, 3))}


df = pd.DataFrame(table_data)
df

연도  매출액  종업원 수
0  2010    1      2
1  2011    4      5
2  2012    9      8
3  2013   16     11
4  2014   25     14
5  2015   36     17
6  2016   49     20
7  2017   64     23
8  2018   81     26
9  2019  100     29

In [71]:
df.head()

연도  매출액  종업원 수
0  2010    1      2
1  2011    4      5
2  2012    9      8
3  2013   16     11
4  2014   25     14

In [72]:
df1 = pd.DataFrame({'봄': [256.5, 264.3, 215.9, 223.2, 312.8],
                    '여름': [770.6, 567.5, 599.8, 387.1, 446.2],
                    '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
                    '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]},
                    index=['2012', '2013', '2014', '2015', '2016'])
df1

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [73]:
df1.sum(0)

봄     1272.7
여름    2771.2
가을    1517.1
겨울     493.3
dtype: float64

In [74]:
df1.sum(1)

2012    1529.9
2013    1122.9
2014    1185.7
2015     967.1
2016    1248.7
dtype: float64

In [75]:
df1.describe().T

count    mean         std    min    25%    50%    75%    max
봄     5.0  254.54   38.628267  215.9  223.2  256.5  264.3  312.8
여름    5.0  554.24  148.888895  387.1  446.2  567.5  599.8  770.6
가을    5.0  303.42   67.358496  231.2  247.7  293.1  363.5  381.6
겨울    5.0   98.66   30.925523   59.9   76.9  108.1  109.1  139.3

In [76]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 2012 to 2016
Data columns (total 4 columns):
봄     5 non-null float64
여름    5 non-null float64
가을    5 non-null float64
겨울    5 non-null float64
dtypes: float64(4)
memory usage: 360.0+ bytes


In [77]:
df1.loc['2013' : , '봄' : "가을"][:3]

봄     여름     가을
2013  264.3  567.5  231.2
2014  215.9  599.8  293.1
2015  223.2  387.1  247.7

In [78]:
df1 = pd.DataFrame({'Class1': [95, 92, 98, 100],
                    'Class2': [91, 93, 98, 100]})
df1

Class1  Class2
0      95      91
1      92      93
2      98      98
3     100     100

In [79]:
df2 = pd.DataFrame({'Class1': [76, 88],
                    'Class2': [100, 100]})
df2

Class1  Class2
0      76     100
1      88     100

In [80]:
df1.append(df2, ignore_index=True)
#ignore_index 를 하지않으면 0,1,2,3,0,1 로 인덱스가 추가됨

Class1  Class2
0      95      91
1      92      93
2      98      98
3     100     100
4      76     100
5      88     100

In [81]:
df3 = pd.DataFrame({'Class1': [80,10], 'Class3': [50, 60]})
df3

Class1  Class3
0      80      50
1      10      60

In [82]:
df1.append(df3, ignore_index=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


Class1  Class2  Class3
0      95    91.0     NaN
1      92    93.0     NaN
2      98    98.0     NaN
3     100   100.0     NaN
4      80     NaN    50.0
5      10     NaN    60.0

In [83]:
df4 = pd.DataFrame({'Class3': [92,93,94,91,99]})
df4

Class3
0      92
1      93
2      94
3      91
4      99

In [84]:
df1.join(df4,how = 'outer')

Class1  Class2  Class3
0    95.0    91.0      92
1    92.0    93.0      93
2    98.0    98.0      94
3   100.0   100.0      91
4     NaN     NaN      99

In [85]:
import random
month_list = [str(i)+'월' for i in range(1,5)]

prod_A, prod_B, prod_C, prod_D = [np.random.randint(50, 100, size=4) for i in range(4)]


df_A_B = pd.DataFrame({'판매월': month_list, 
                       '제품A': prod_A,
                       '제품B': prod_B})
df_A_B

판매월  제품A  제품B
0  1월   98   75
1  2월   84   87
2  3월   63   99
3  4월   52   95

In [86]:
prod_E, prod_F = [np.random.randint(50, 100, size=4) for i in range(2)]
df_E_F = pd.DataFrame({'판매월': ['3월', '4월', '5월', '6월'],
                       '제품E': prod_E,
                       '제품F': prod_F})
df_E_F

판매월  제품E  제품F
0  3월   93   82
1  4월   96   78
2  5월   95   69
3  6월   86   57

In [87]:
df_C_D = pd.DataFrame({'판매월': month_list,
                       '제품C': prod_C,
                       '제품D': prod_D})
df_C_D

판매월  제품C  제품D
0  1월   84   81
1  2월   73   52
2  3월   75   55
3  4월   50   94

In [88]:
df_A_B.merge(df_E_F, how='outer', on="판매월")

판매월   제품A   제품B   제품E   제품F
0  1월  98.0  75.0   NaN   NaN
1  2월  84.0  87.0   NaN   NaN
2  3월  63.0  99.0  93.0  82.0
3  4월  52.0  95.0  96.0  78.0
4  5월   NaN   NaN  95.0  69.0
5  6월   NaN   NaN  86.0  57.0

In [89]:
import os
BASE_DIR = os.getcwd()
DATASET_PATH = os.path.join(BASE_DIR, "datasets\\201904")
print(DATASET_PATH)

C:\Users\student\Documents\python project\datasets\201904


In [90]:
file1 = os.path.join(DATASET_PATH,"2019-04-30.csv")
df1 = pd.read_csv(file1, error_bad_lines = False)
df1.head()

b'Skipping line 18081: expected 8 fields, saw 11\n'


2019-04-30  1545587997  C013010    점퍼  \
0  2019-04-30   147567876  C013020   티셔츠   
1  2019-04-30   897756527  A011060    땅콩   
2  2019-04-30   410494691  A019050    간장   
3  2019-04-30   223173815  C011020  남자상의   
4  2019-04-30  1173935366  A019180  즉석식품   

                      캘빈클라인진 19SS 신상 여성 항공점퍼 J211287  99500  Unnamed: 6  \
0           [모다아울렛][티엔지티]그레이 라운드넥 면 긴팔티셔츠TGTS9A103G2  55200         NaN   
1                     간단한 맥주안주 마른 군것질 견과 꿀땅콩 453g 간단  10970         NaN   
2                   간장(진 사조 옹가네 1.8L)X8 간장 진간장 식자재 업  36870         NaN   
3  (색상 : 곤색 | 사이즈 : XL) FSSF18036 선염체크 버튼다운 남방 남자...  41070         NaN   
4  (냉동)금호 쌀떡꼬치900g(10p)x15개(1box) 쌀떡꼬치 튀김류 떡꼬치 가공...  89160         NaN   

   Unnamed: 7  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN

In [91]:
df2 = df1.head()
df2.to_csv("temp.csv",encoding="cp949")

In [92]:
date_index = pd.date_range('2019-04-01','2019-04-30')
date_index

DatetimeIndex(['2019-04-01', '2019-04-02', '2019-04-03', '2019-04-04',
               '2019-04-05', '2019-04-06', '2019-04-07', '2019-04-08',
               '2019-04-09', '2019-04-10', '2019-04-11', '2019-04-12',
               '2019-04-13', '2019-04-14', '2019-04-15', '2019-04-16',
               '2019-04-17', '2019-04-18', '2019-04-19', '2019-04-20',
               '2019-04-21', '2019-04-22', '2019-04-23', '2019-04-24',
               '2019-04-25', '2019-04-26', '2019-04-27', '2019-04-28',
               '2019-04-29', '2019-04-30'],
              dtype='datetime64[ns]', freq='D')

In [93]:
date_index_list = []
for i in range(len(date_index)):
    date_index_list.append(date_index[i].date())

In [94]:
date_index[0].astype(str)

AttributeError: 'Timestamp' object has no attribute 'astype'

In [98]:

df = pd.DataFrame([pd.date_range('2019-04-01','2019-04-30')])

df1 = df.T

df2 = df1[0].astype(str)


for i in range(len(df2)):
    df2[i] = df2[i] + ".csv"

In [112]:

file1 = os.path.join(DATASET_PATH,"2019-04-30.csv")
df1 = pd.read_csv(file1, error_bad_lines = False, header=None)
df1 = df1.head()

for i in range(len(df2)):
    file = os.path.join(DATASET_PATH, df2[i])
    df = pd.read_csv(file, error_bad_lines = False,header=None)
    df1 = df1.append(df.head())
print(df1)

b'Skipping line 18081: expected 8 fields, saw 11\n'
b'Skipping line 36560: expected 8 fields, saw 11\n'
b'Skipping line 222462: expected 8 fields, saw 11\n'
b'Skipping line 27894: expected 8 fields, saw 11\n'
b'Skipping line 45907: expected 8 fields, saw 11\n'
b'Skipping line 45538: expected 8 fields, saw 11\n'
b'Skipping line 89789: expected 8 fields, saw 11\n'
b'Skipping line 219259: expected 8 fields, saw 11\n'
b'Skipping line 129303: expected 8 fields, saw 11\n'
b'Skipping line 272309: expected 8 fields, saw 11\n'
b'Skipping line 211460: expected 8 fields, saw 11\n'
b'Skipping line 57879: expected 8 fields, saw 11\n'
b'Skipping line 170099: expected 8 fields, saw 11\n'
b'Skipping line 168991: expected 8 fields, saw 11\n'
b'Skipping line 61227: expected 8 fields, saw 11\n'
b'Skipping line 139967: expected 8 fields, saw 11\n'
b'Skipping line 61480: expected 8 fields, saw 11\n'
b'Skipping line 77728: expected 8 fields, saw 11\n'
b'Skipping line 271889: expected 8 fields, saw 11\n'
b'S

             0           1        2       3  \
0   2019-04-30  1545587997  C013010      점퍼   
1   2019-04-30   147567876  C013020     티셔츠   
2   2019-04-30   897756527  A011060      땅콩   
3   2019-04-30   410494691  A019050      간장   
4   2019-04-30   223173815  C011020    남자상의   
0   2019-04-01  2142932948  C011020    남자상의   
1   2019-04-01  1812194343  C013020     티셔츠   
2   2019-04-01   954865871  C014010     아동복   
3   2019-04-01   853175004  A021010      커피   
4   2019-04-01   826899644  A019050      간장   
0   2019-04-02   273252144  L012110   색조화장품   
1   2019-04-02   512422932  A019150      김치   
2   2019-04-02   674883495  C013010      점퍼   
3   2019-04-02   176404680  C014010     아동복   
4   2019-04-02    74807563  C011040    남자하의   
0   2019-04-03  1584339633  C014020     유아복   
1   2019-04-03   364473576  C011040    남자하의   
2   2019-04-03   717055202  L012110   색조화장품   
3   2019-04-03   846186979  C013010      점퍼   
4   2019-04-03   233062096  A018050     비스킷   
0   2019-04-0

In [108]:
initial_file = os.path.join(DATASET_PATH, "2019-04-01.csv")
o_df = pd.read_csv(initial_file, header = None, error_bad_lines = False)

for x in pd.date_range('2019-04-02',periods = 29):
    date = x.strftime('%Y-%m-%d')
    filename = "{}.csv".format(date)
    
    filepath = os.path.join(DATASET_PATH,filename)
    pd.read_csv(filepath, header= None, error_bad_lines = False)
    o_df = o_df.append(df)

b'Skipping line 36560: expected 8 fields, saw 11\n'
b'Skipping line 222462: expected 8 fields, saw 11\n'
b'Skipping line 27894: expected 8 fields, saw 11\n'
b'Skipping line 45907: expected 8 fields, saw 11\n'
b'Skipping line 45538: expected 8 fields, saw 11\n'
b'Skipping line 89789: expected 8 fields, saw 11\n'
b'Skipping line 219259: expected 8 fields, saw 11\n'
b'Skipping line 129303: expected 8 fields, saw 11\n'
b'Skipping line 272309: expected 8 fields, saw 11\n'
b'Skipping line 211460: expected 8 fields, saw 11\n'
b'Skipping line 57879: expected 8 fields, saw 11\n'
b'Skipping line 170099: expected 8 fields, saw 11\n'
b'Skipping line 168991: expected 8 fields, saw 11\n'
b'Skipping line 61227: expected 8 fields, saw 11\n'
b'Skipping line 139967: expected 8 fields, saw 11\n'
b'Skipping line 61480: expected 8 fields, saw 11\n'
b'Skipping line 77728: expected 8 fields, saw 11\n'
b'Skipping line 271889: expected 8 fields, saw 11\n'
b'Skipping line 223096: expected 8 fields, saw 11\n'
b'